version: '2'
services:
    dockcheck-app:
        image: dockcheck
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://dockcheck-mysql:3306/dockcheck?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    dockcheck-mysql:
        extends:
            file: mysql.yml
            service: dockcheck-mysql
